hrogerdev/GO_FAST

app/assets/stylesheets/components/_cardindexmules.scss
app/assets/stylesheets/components/_cardsgrid.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_searchbar.scss
app/assets/stylesheets/components/_titles.scss
app/controllers/mules_controller.rb
app/views/mules/index.html.erb
config/routes.rb
test/controllers/mules_controller_test.rb

- The view for mule's index was created 
- with cards for each mule
- with a searchbar that is still not functional
-The title of the cards will be the location but I first need

Create mules index

---

app/assets/stylesheets/components/_cardmuleshow.scss
app/assets/stylesheets/components/_index.scss
app/controllers/mules_controller.rb
app/views/mules/show.html.erb

Avatar of the user with the rate and it's info

create show for mule

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cardindexmules.scss
app/views/mules/index.html.erb
app/views/mules/show.html.erb
db/seeds.rb

Created the link between the mules from index and the show. Added the button to go from the mule to the index.

Link between mule show and index

---

config/routes.rb

Created the route show for a new offer

create route show for offer

---

app/assets/stylesheets/components/_button.scss
app/controllers/offers_controller.rb
app/views/offers/show.html.erb

Created view show for the new offers

create view show for offer

---

app/assets/stylesheets/components/_cardmuleshow.scss
app/assets/stylesheets/components/_index.scss
app/controllers/mules_controller.rb
app/controllers/offers_controller.rb
app/views/mules/show.html.erb

Form to create a new offer at the show view of a mule

create new offer

---

app/views/mules/index.html.erb
app/views/mules/show.html.erb

Updated the index and the show of the mules with the correct profile picture in the img

add the profile picture to the img

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb

add a logo to the navbar

---

db/seeds.rb

add photos to seed

---

app/controllers/mules_controller.rb
app/controllers/offers_controller.rb
app/views/offers/show.html.erb

Created the approve method in the offer controller and added the link to the accept button in the offer show view

add option approve offer

---

app/controllers/offers_controller.rb
app/views/offers/show.html.erb

Created method refused in the controller and added the link in the offer show view

add option refuse offer

---

app/controllers/offers_controller.rb

a tiny fix : add a missing end in the code after I broke it during conflict resolution

fix the code with a missing 'end'

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_offer-profile-card.scss
app/controllers/mules_controller.rb
app/controllers/profiles_controller.rb
app/views/profiles/show.html.erb

.Profile cards like train tickets

Offers in profile

---

app/views/offers/show.html.erb

Added the if method in the view show for and offer to only display the buttons if an offer is still pending

update offer show view to display buttons only if not pending

---

app/views/layouts/application.html.erb

Added the picture of current user to the nav bar avatar

add current user pic to avatar

---

app/views/profiles/show.html.erb

erase comment

---

app/controllers/offers_controller.rb
app/views/offers/show.html.erb

Solved issue with the buttons in the offer show

solved the issue with offer buttons

---

app/views/profiles/show.html.erb

The profile picture shows the user photo and added username and description in the details.

update profile show view pic and info

---

app/assets/stylesheets/components/_banner-login.scss
app/views/pages/home.html.erb

modify the tagline on home page

modify the homepage tagline

---

app/controllers/offers_controller.rb
app/views/offers/show.html.erb

Changed the offer controller so the current user cant accept or reject the offer he posted. Changed the offer view so if the user posted the offer he doesnt see the options but the status.

remove offer options for owner

---

app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Set the logo as a link
Redirect to home page when clicked even if user is logged

Logo to home

---

app/views/profiles/show.html.erb

add the default image to the profile if user didn't updated one

add a default photo for users that dont have one attached

---

app/views/mules/show.html.erb

add some ugly logos in thz form

tiny modification in the offer form

---

app/assets/stylesheets/components/_banner-login.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

tiny modification on home page style

Home page style

---

app/views/mules/index.html.erb

mules cards clickable again

---

app/assets/stylesheets/components/_cardindexmules.scss
app/assets/stylesheets/components/_titles.scss
app/controllers/mules_controller.rb
app/views/mules/index.html.erb

Changed the style of the index page. (cards, colors and fonts)

Modify mules index view
